server: #tomcat端口号
  port: 8160

#微信认证资质
wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台
    redirect_url: http://localhost:8160/api/ucenter/wx/callback