mybatis:
  type-aliases-package: com.atguigu.pojo
  mapper-locations: classpath:com/atguigu/dao/*.xml
spring:
  resources:
    static-locations: classpath:/webapp/
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springboot?autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver