spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?autoReconnect=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  redis:
    host: 192.168.2.118
    port: 6379
mybatis:
  type-aliases-package: com.atguigu.pojo
server:
  port: 10002